class Word {
  final String text;
  final String word;
  final String imageWord;
  final String sound;
  final int correct_number;

  Word({required this.text, required this.word, required this.imageWord, required this.sound, required this.correct_number});
}
class WordList {
  static List<Word> getTasks() {
    return [
      Word(
        word: 'assets/Alphtablet/А.jpg',
        imageWord: 'assets/imageWord/А.jpg',
        text: 'Арбуз',
        sound: 'Sound/lernwordSound/А.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/Б.jpg',
        imageWord: 'assets/imageWord/Б.jpg',
        text: 'Берёза',
        sound: 'Sound/lernwordSound/Б.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/В.jpg',
        imageWord: 'assets/imageWord/В.jpg',
        text: 'Вишня',
        sound: 'Sound/lernwordSound/В.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/Г.jpg',
        imageWord: 'assets/imageWord/Г.jpg',
        text: 'Гном',
        sound: 'assets/Sound/lernwordSound/Г.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/Д.jpg',
        imageWord: 'assets/imageWord/Д.jpg',
        text: 'Дверь',
        sound: 'Sound/lernwordSound/Д.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/Е.jpg',
        imageWord: 'assets/imageWord/Е.jpg',
        text: 'Ель',
        sound: 'Sound/lernwordSound/Е.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/Ё.jpg',
        imageWord: 'assets/imageWord/Ё.jpg',
        text: 'Ёж',
        sound: 'Sound/lernwordSound/Ё.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/Ж.jpg',
        imageWord: 'assets/imageWord/Ж.jpg',
        text: 'Жираф',
        sound: 'Sound/lernwordSound/Ж.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/З.jpg',
        imageWord: 'assets/imageWord/З.jpg',
        text: 'Зебра',
        sound: 'Sound/lernwordSound/З.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/И.jpg',
        imageWord: 'assets/imageWord/И.jpg',
        text: 'Ива',
        sound: 'Sound/lernwordSound/И.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/Й.jpg',
        imageWord: 'assets/imageWord/Й.jpg',
        text: 'Йогурт',
        sound: 'Sound/lernwordSound/Й.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/К.jpg',
        imageWord: 'assets/imageWord/К.jpg',
        text: 'Кедр',
        sound: 'Sound/lernwordSound/К.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/Л.jpg',
        imageWord: 'assets/imageWord/Л.jpg',
        text: 'Лошадь',
        sound: 'Sound/lernwordSound/Л.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/М.jpg',
        imageWord: 'assets/imageWord/М.jpg',
        text: 'Море',
        sound: 'Sound/lernwordSound/М.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/Н.jpg',
        imageWord: 'assets/imageWord/Н.jpg',
        text: 'Носорог',
        sound: 'Sound/lernwordSound/Н.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/О.jpg',
        imageWord: 'assets/imageWord/О.jpg',
        text: 'Озеро',
        sound: 'Sound/lernwordSound/О.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/П.jpg',
        imageWord: 'assets/imageWord/П.jpg',
        text: 'Пеликан',
        sound: 'Sound/lernwordSound/П.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/Р.jpg',
        imageWord: 'assets/imageWord/Р.jpg',
        text: 'Рыбак',
        sound: 'Sound/lernwordSound/Р.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/С.jpg',
        imageWord: 'assets/imageWord/С.jpg',
        text: 'Сорняк',
        sound: 'Sound/lernwordSound/С.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/Т.jpg',
        imageWord: 'assets/imageWord/Т.jpg',
        text: 'Тигр',
        sound: 'Sound/lernwordSound/Т.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/У.jpg',
        imageWord: 'assets/imageWord/У.jpg',
        text: 'Утка',
        sound: 'Sound/lernwordSound/У.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/Ф.jpg',
        imageWord: 'assets/imageWord/Ф.jpg',
        text: 'Фартук',
        sound: 'Sound/lernwordSound/Ф.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/Х.jpg',
        imageWord: 'assets/imageWord/Х.jpg',
        text: 'Хамелеон',
        sound: 'Sound/lernwordSound/Х.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/Ц.jpg',
        imageWord: 'assets/imageWord/Ц.jpg',
        text: 'Цапля',
        sound: 'Sound/lernwordSound/Ц.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/Ч.jpg',
        imageWord: 'assets/imageWord/Ч.jpg',
        text: 'Черепаха',
        sound: 'Sound/lernwordSound/Ч.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/Ш.jpg',
        imageWord: 'assets/imageWord/Ш.jpg',
        text: 'Шмель',
        sound: 'Sound/lernwordSound/Ш.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/Щ.jpg',
        imageWord: 'assets/imageWord/Щ.jpg',
        text: 'Щука',
        sound: 'Sound/lernwordSound/Щ.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/Ъ.jpg',
        imageWord: '',
        text: 'Твёрдый знак',
        sound: 'Sound/lernwordSound/Ъ.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/Ы.jpg',
        imageWord: '',
        text: 'Буква Ы',
        sound: 'Sound/lernwordSound/Ы.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/Ь.jpg',
        imageWord: '',
        text: 'Мягкий знак',
        sound: 'Sound/lernwordSound/Ь.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/Э.jpg',
        imageWord: 'assets/imageWord/Э.jpg',
        text: 'Эскимо',
        sound: 'Sound/lernwordSound/Э.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/Ю.jpg',
        imageWord: 'assets/imageWord/Ю.jpg',
        text: 'Юла',
        sound: 'Sound/lernwordSound/Ю.mp3',
        correct_number: 4,
      ),
      Word(
        word: 'assets/Alphtablet/Я.jpg',
        imageWord: 'assets/imageWord/Я.jpg',
        text: 'Ягоды',
        sound: 'Sound/lernwordSound/Я.mp3',
        correct_number: 4,
      ),
    ];
  }
}